find_path(	CFITSIO_INCLUDE_DIR fitsio.h
			PATH_SUFFIXES cfitsio
			PATHS
			$ENV{CFITSIO})

find_library(	CFITSIO_LIBRARIES NAMES cfitsio
				PATHS
				$ENV{CFITSIO})			
		
IF(CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARIES)
	set(CFITSIO_FOUND TRUE)
ELSE(CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARIES)
	set(CFITSIO_FOUND FALSE)
ENDIF(CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARIES)

mark_as_advanced(CFITSIO_INCLUDE_DIR CFITSIO_LIBRARIES)


